name: gitleaks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        

  process-results:
    name: Process Results
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run ID and Repository
        run: |
          export repo="${{ github.repository }}"
          export workflow_run_id="${{ github.run_id }}"
          echo "$repo"
          echo "$workflow_run_id"
          export workflow_run_id="${{ workflow_job_id }}"
          echo "$workflow_job_id"
          
          
      - name: Execute Commands
        run: |
          token="${{ secrets.GIT }}"
          # Получение списка артефактов
          sum=$(curl -s -H "Authorization: token $token" "https://github.com/$repo/actions/runs/$workflow_run_id/jobs/$workflow_job_id/summary_raw")
          echo "$sum"
          
