name: gitleaks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install BeautifulSoup
        run: pip install beautifulsoup4
        
      - uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - id: exp
        uses: pl-strflt/job-summary-url-action@v1
      
      - name: Get job_html_url
        run: |
          job_html_url="${{ steps.exp.outputs.job_summary_url }}"
          echo "Job HTML URL: $job_html_url"
          # Извлечение имен файлов с использованием регулярных выражений
          files=$(curl -s "$job_html_url" | grep -oE 'https:\/\/github\.com\/darliiin\/test\/blob\/[^"]*' | cut -d/ -f7-)
          echo "Files: $files"
     
