name: gitleaks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.get-details.outputs.job_html}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - id: exp
        uses: pl-strflt/job-summary-url-action@v1
      
      - name: Get file
        run: |
          job_html_url="${{ steps.exp.outputs.job_summary_url }}"
          echo "Job HTML URL: $job_html_url"
