# Gitleaks is a tool for detecting and preventing hardcoded secrets(i.e. ssh pem keys, our files ending with .secrets).
# we use our own gitleaks configuration gitleaks.toml, it is located at the root of the repository, 
# automatically detected and used by gitleaks-action.

name: gitleaks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  scan:
    name: gitleaks
    runs-on: saritasa-rocks-eks
    steps: 
      - name: Run a step
        id: step1
        run: |
          echo "Some data" > output.txt
          exit 1
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: step1-output
      
      - name: Display content of output.txt
        run: cat step1-output/output.txt
